### ISSUE TITLE
Checking broken links against a plain-text only email results in an error

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-inbox-mailgun#11]
### Repro Steps
1. Send a [plain-text email](https://www.lifewire.com/how-to-send-a-message-in-plain-text-from-gmail-1171963) to `aaaa0000-bbbb-1111-cccc-2222dddd3333@thisisjust.atomatest.com` which contains a single, broken link (e.g. `https://www.lkjslkjdsf.biz`)
2. Run the following command: `crank cog:step automatoninc/inbox-mailgun --step=EmailLinksValidationStep` entering the email address above and `1` when prompted.

### Expected Result
The step should come back red / fail and list the URL just once under "Plain Text"

### Actual Result
The step results in a `TypeError: Cannot read property 'match' of undefined` error.

![Screen Shot 2019-12-11 at 4 48 45 PM](https://user-images.githubusercontent.com/3496491/70673144-66feae80-1c36-11ea-9495-e362c2781256.png)

**Comment by iamEAP** [comment]
Merged fixes can be tested via:
```sh
crank cog:install automatoninc/inbox-mailgun:dev-v72 --ignore-auth --force
```

**Comment by roanlibelo** [comment]
Upon checking this issue, I encountered this.

![image](https://user-images.githubusercontent.com/54615569/72247100-24facb00-362f-11ea-850e-c0448c227ea4.png)
